### PR TITLE
Upgrade to Angular 14.2.10 and Sign-In Widget v7

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
It seems like something needs to change in the widget's configuration. When I try to login, I get an error on the login page.

```
POST https://dev-17700857.okta.com/oauth2/default/v1/interact 400
...
home.component.html:20 ERROR Error: Uncaught (in promise): OAuthError: The client is not authorized to use the provided grant type. Configured grant types: [authorization_code].
OAuthError: The client is not authorized to use the provided grant type. Configured grant types: [authorization_code].
```

**Comment by mraible** [comment]
@alisaduncan It looks like there are [some changes needed](https://github.com/okta/okta-signin-widget/blob/master/MIGRATING.md) for the latest version of the sign-in widget. Can you please take a look and see if you can fix when you get a chance?

**Comment by alisaduncan** [comment]
@mraible I'll take a look tomorrow

**Comment by alisaduncan** [comment]
@mraible This isn't an Angular code issue. I'm guessing we'll have this wherever the SIW is used. Starting discussion on team slack

**Comment by mraible** [comment]
@alisaduncan True, but it is an Okta CLI + Sign-In Widget issue. We could change the SIW's configuration to have `useClassicEngine`. I think that would fix things based on the [migration guide](https://github.com/okta/okta-signin-widget/blob/master/MIGRATING.md#migrating-from-6x-to-7x). 

AFAIK, this is the only example we have for the CLI that uses the Sign-In Widget. I often use it as a demo of how not to do things. 😉 

It's only referenced in [one blog post](https://developer.okta.com/blog/2020/12/03/angular-okta), and I just discovered it has a typo in it. Since we've never been notified, it's possible no one has ever tried this example.

Fix for typo: https://github.com/oktadev/okta-blog/pull/1307

**Comment by alisaduncan** [comment]
Yes, it does look like adding `useClassEngine` will resolve it for right now, but not a long-term fix.

**Comment by alisaduncan** [comment]
Closing this PR as we will no longer update this branch with the latest versions of Okta & Angular libs. The recommended approach is to use the Okta-hosted redirect flow, which the `main` branch supports.

**Pull request closed without merging**
